import dotenv from 'dotenv';
dotenv.config();

import mongoose from 'mongoose';
import Verb from './models/Verb';
import Noun from './models/Noun';
import Adjective from './models/Adjective';
import Sentence from './models/Sentence';

const VERBS: Array<[string, string, string, string, string]> = [
  ['entwickeln', 'develop', 'Entwicklung', 'Ich entwickle skalierbare Backend-Systeme mit Laravel.', 'hat entwickelt'],
  ['implementieren', 'implement', 'Entwicklung', 'Ich implementiere neue Features im aktuellen Sprint.', 'hat implementiert'],
  ['programmieren', 'program / code', 'Entwicklung', 'Ich programmiere täglich in PHP und Python.', 'hat programmiert'],
  ['schreiben', 'write (code)', 'Entwicklung', 'Ich schreibe sauberen, wartbaren Code.', 'hat geschrieben'],
  ['erstellen', 'create', 'Entwicklung', 'Ich erstelle eine neue API-Schnittstelle.', 'hat erstellt'],
  ['bauen', 'build', 'Entwicklung', 'Wir bauen gerade ein neues Modul.', 'hat gebaut'],
  ['aufbauen', 'set up / build up', 'Entwicklung', 'Ich habe die CI/CD-Pipeline aufgebaut.', 'hat aufgebaut'],
  ['erweitern', 'extend / expand', 'Entwicklung', 'Ich erweitere die bestehende API.', 'hat erweitert'],
  ['anpassen', 'adjust / adapt', 'Entwicklung', 'Ich passe den Code an die neuen Anforderungen an.', 'hat angepasst'],
  ['ändern', 'change', 'Entwicklung', 'Ich ändere die Datenbankstruktur.', 'hat geändert'],
  ['aktualisieren', 'update', 'Entwicklung', 'Ich aktualisiere die Abhängigkeiten im Projekt.', 'hat aktualisiert'],
  ['verbessern', 'improve', 'Entwicklung', 'Ich verbessere die Performance der Abfragen.', 'hat verbessert'],
  ['optimieren', 'optimise', 'Entwicklung', 'Ich optimiere die Ladezeit der Seite.', 'hat optimiert'],
  ['refaktorieren', 'refactor', 'Entwicklung', 'Ich refaktoriere alten Code, um ihn lesbarer zu machen.', 'hat refaktoriert'],
  ['vereinfachen', 'simplify', 'Entwicklung', 'Ich vereinfache die Logik in dieser Funktion.', 'hat vereinfacht'],
  ['strukturieren', 'structure', 'Entwicklung', 'Ich strukturiere das Projekt nach Clean-Code-Prinzipien.', 'hat strukturiert'],
  ['trennen', 'separate', 'Entwicklung', 'Ich trenne Business-Logik von der Datenbankschicht.', 'hat getrennt'],
  ['verbinden', 'connect', 'Entwicklung', 'Ich verbinde das Frontend mit der REST-API.', 'hat verbunden'],
  ['integrieren', 'integrate', 'Entwicklung', 'Ich integriere einen externen Service über eine API.', 'hat integriert'],
  ['nutzen', 'use', 'Entwicklung', 'Ich nutze Docker für die lokale Entwicklung.', 'hat genutzt'],
  ['verwenden', 'use / utilise', 'Entwicklung', 'Ich verwende TypeScript statt JavaScript.', 'hat verwendet'],
  ['laden', 'load', 'Entwicklung', 'Die Seite lädt alle Daten beim Start.', 'hat geladen'],
  ['speichern', 'save / store', 'Entwicklung', 'Ich speichere die Daten in der Datenbank.', 'hat gespeichert'],
  ['ausgeben', 'output / return', 'Entwicklung', 'Die Funktion gibt ein JSON-Objekt aus.', 'hat ausgegeben'],
  ['zurückgeben', 'return (a value)', 'Entwicklung', 'Die Methode gibt einen Boolean zurück.', 'hat zurückgegeben'],
  ['aufrufen', 'call (a function)', 'Entwicklung', 'Ich rufe die API-Methode auf.', 'hat aufgerufen'],
  ['definieren', 'define', 'Entwicklung', 'Ich definiere eine neue Klasse.', 'hat definiert'],
  ['initialisieren', 'initialise', 'Entwicklung', 'Ich initialisiere das Objekt im Konstruktor.', 'hat initialisiert'],
  ['instanziieren', 'instantiate', 'Entwicklung', 'Ich instanziiere die Klasse im Controller.', 'hat instanziiert'],
  ['überschreiben', 'override', 'Entwicklung', 'Ich überschreibe die Methode der Elternklasse.', 'hat überschrieben'],
  ['importieren', 'import', 'Entwicklung', 'Ich importiere das Modul am Anfang der Datei.', 'hat importiert'],
  ['exportieren', 'export', 'Entwicklung', 'Ich exportiere die Funktion für andere Module.', 'hat exportiert'],
  ['kompilieren', 'compile', 'Entwicklung', 'Ich kompiliere den TypeScript-Code zu JavaScript.', 'hat kompiliert'],
  ['testen', 'test', 'Testing', 'Ich teste die neue Funktion manuell.', 'hat getestet'],
  ['prüfen', 'check / verify', 'Testing', 'Ich prüfe, ob die API korrekte Daten zurückgibt.', 'hat geprüft'],
  ['überprüfen', 'review / verify', 'Testing', 'Ich überprüfe den Code im Review.', 'hat überprüft'],
  ['validieren', 'validate', 'Testing', 'Ich validiere die Eingabe des Benutzers.', 'hat validiert'],
  ['debuggen', 'debug', 'Testing', 'Ich debugge den Fehler im Backend.', 'hat gedebugt'],
  ['analysieren', 'analyse', 'Testing', 'Ich analysiere die Logs, um das Problem zu finden.', 'hat analysiert'],
  ['untersuchen', 'investigate', 'Testing', 'Ich untersuche den Fehler im Produktionssystem.', 'hat untersucht'],
  ['reproduzieren', 'reproduce', 'Testing', 'Ich versuche, den Fehler zu reproduzieren.', 'hat reproduziert'],
  ['simulieren', 'simulate', 'Testing', 'Ich simuliere eine Benutzeranfrage im Test.', 'hat simuliert'],
  ['messen', 'measure', 'Testing', 'Ich messe die Antwortzeit der API.', 'hat gemessen'],
  ['vergleichen', 'compare', 'Testing', 'Ich vergleiche den erwarteten mit dem tatsächlichen Wert.', 'hat verglichen'],
  ['loggen', 'log', 'Testing', 'Ich logge die Anfragen für das Debugging.', 'hat geloggt'],
  ['sicherstellen', 'ensure', 'Testing', 'Ich stelle sicher, dass keine Regression entsteht.', 'hat sichergestellt'],
  ['deployen', 'deploy', 'Deployment', 'Ich deploye die neue Version auf den Staging-Server.', 'hat deployed'],
  ['automatisieren', 'automate', 'Deployment', 'Ich automatisiere das Deployment mit GitHub Actions.', 'hat automatisiert'],
  ['konfigurieren', 'configure', 'Deployment', 'Ich konfiguriere den Nginx-Webserver.', 'hat konfiguriert'],
  ['einrichten', 'set up', 'Deployment', 'Ich richte die neue Entwicklungsumgebung ein.', 'hat eingerichtet'],
  ['installieren', 'install', 'Deployment', 'Ich installiere die Abhängigkeiten mit npm install.', 'hat installiert'],
  ['starten', 'start', 'Deployment', 'Ich starte den Docker-Container.', 'hat gestartet'],
  ['stoppen', 'stop', 'Deployment', 'Ich stoppe den Server für das Update.', 'hat gestoppt'],
  ['neustarten', 'restart', 'Deployment', 'Ich starte den Service neu nach der Konfiguration.', 'hat neugestartet'],
  ['pushen', 'push', 'Deployment', 'Ich pushe den Code ins Repository.', 'hat gepusht'],
  ['pullen', 'pull', 'Deployment', 'Ich pulle die neuesten Änderungen vom Remote.', 'hat gepullt'],
  ['mergen', 'merge', 'Deployment', 'Ich merge den Feature-Branch in den Main-Branch.', 'hat gemergt'],
  ['skalieren', 'scale', 'Deployment', 'Wir skalieren den Service bei hoher Last.', 'hat skaliert'],
  ['überwachen', 'monitor', 'Deployment', 'Ich überwache die CPU-Auslastung in Produktion.', 'hat überwacht'],
  ['zurückrollen', 'roll back', 'Deployment', 'Wir rollen das Update zurück, weil es einen Fehler gab.', 'hat zurückgerollt'],
  ['migrieren', 'migrate', 'Deployment', 'Ich migriere die Datenbank auf die neue Version.', 'hat migriert'],
  ['abfragen', 'query', 'Datenbank', 'Ich frage die Tabelle mit einem JOIN ab.', 'hat abgefragt'],
  ['filtern', 'filter', 'Datenbank', 'Ich filtere die Ergebnisse nach Datum.', 'hat gefiltert'],
  ['sortieren', 'sort', 'Datenbank', 'Ich sortiere die Liste nach dem Namen.', 'hat sortiert'],
  ['aggregieren', 'aggregate', 'Datenbank', 'Ich aggregiere die Verkaufszahlen pro Monat.', 'hat aggregiert'],
  ['einfügen', 'insert', 'Datenbank', 'Ich füge einen neuen Datensatz ein.', 'hat eingefügt'],
  ['löschen', 'delete', 'Datenbank', 'Ich lösche veraltete Einträge aus der Tabelle.', 'hat gelöscht'],
  ['verarbeiten', 'process', 'Datenbank', 'Ich verarbeite die eingehenden Daten vor dem Speichern.', 'hat verarbeitet'],
  ['parsen', 'parse', 'Datenbank', 'Ich parse die XML-Antwort der API.', 'hat geparst'],
  ['mappen', 'map', 'Datenbank', 'Ich mappe die Datenbankfelder auf das DTO.', 'hat gemappt'],
  ['konvertieren', 'convert', 'Datenbank', 'Ich konvertiere das Datum in das ISO-Format.', 'hat konvertiert'],
  ['normalisieren', 'normalise', 'Datenbank', 'Ich normalisiere die Datenbankstruktur.', 'hat normalisiert'],
  ['indizieren', 'index', 'Datenbank', 'Ich indiziere die häufig genutzten Felder.', 'hat indiziert'],
  ['cachen', 'cache', 'Datenbank', 'Ich cache die häufigen Anfragen mit Redis.', 'hat gecacht'],
  ['synchronisieren', 'synchronise', 'Datenbank', 'Ich synchronisiere die Daten zwischen zwei Systemen.', 'hat synchronisiert'],
  ['verschlüsseln', 'encrypt', 'Datenbank', 'Ich verschlüssele die Passwörter mit bcrypt.', 'hat verschlüsselt'],
  ['hashen', 'hash', 'Datenbank', 'Ich hashe das Passwort vor dem Speichern.', 'hat gehasht'],
  ['ausführen', 'execute / run', 'System', 'Ich führe den Befehl im Terminal aus.', 'hat ausgeführt'],
  ['authentifizieren', 'authenticate', 'System', 'Ich authentifiziere den Benutzer mit JWT.', 'hat authentifiziert'],
  ['autorisieren', 'authorise', 'System', 'Ich autorisiere den Zugriff auf die Ressource.', 'hat autorisiert'],
  ['absichern', 'secure', 'System', 'Ich sichere die API-Endpunkte ab.', 'hat abgesichert'],
  ['schützen', 'protect', 'System', 'Ich schütze die Route mit einem Middleware.', 'hat geschützt'],
  ['weiterleiten', 'forward / redirect', 'System', 'Ich leite die Anfrage an den richtigen Service weiter.', 'hat weitergeleitet'],
  ['behandeln', 'handle', 'System', 'Ich behandle den Fehler mit einem try-catch-Block.', 'hat behandelt'],
  ['auslösen', 'trigger', 'System', 'Ein Event löst den Webhook aus.', 'hat ausgelöst'],
  ['benachrichtigen', 'notify', 'System', 'Das System benachrichtigt den Nutzer per E-Mail.', 'hat benachrichtigt'],
  ['erklären', 'explain', 'Kommunikation', 'Ich erkläre dem Team, wie die neue Funktion funktioniert.', 'hat erklärt'],
  ['beschreiben', 'describe', 'Kommunikation', 'Ich beschreibe das Problem im Ticket.', 'hat beschrieben'],
  ['besprechen', 'discuss', 'Kommunikation', 'Ich bespreche die Lösung mit dem Team.', 'hat besprochen'],
  ['fragen', 'ask', 'Kommunikation', 'Ich frage den Senior-Entwickler um Rat.', 'hat gefragt'],
  ['kommentieren', 'comment', 'Kommunikation', 'Ich kommentiere den Code mit Erklärungen.', 'hat kommentiert'],
  ['reviewen', 'review', 'Kommunikation', 'Ich reviewe den Pull Request meines Kollegen.', 'hat reviewt'],
  ['abstimmen', 'align / coordinate', 'Kommunikation', 'Ich stimme mich mit dem Team ab.', 'hat abgestimmt'],
  ['empfehlen', 'recommend', 'Kommunikation', 'Ich empfehle, PostgreSQL statt MySQL zu nutzen.', 'hat empfohlen'],
  ['vorschlagen', 'suggest', 'Kommunikation', 'Ich schlage eine andere Lösung vor.', 'hat vorgeschlagen'],
  ['informieren', 'inform', 'Kommunikation', 'Ich informiere das Team über das neue Deployment.', 'hat informiert'],
  ['planen', 'plan', 'Planung', 'Ich plane die Aufgaben für den Sprint.', 'hat geplant'],
  ['schätzen', 'estimate', 'Planung', 'Ich schätze die Komplexität der Aufgabe.', 'hat geschätzt'],
  ['priorisieren', 'prioritise', 'Planung', 'Ich priorisiere die wichtigsten Tasks.', 'hat priorisiert'],
  ['entscheiden', 'decide', 'Planung', 'Ich entscheide mich für eine Microservice-Architektur.', 'hat entschieden'],
  ['evaluieren', 'evaluate', 'Planung', 'Ich evaluiere verschiedene Frameworks.', 'hat evaluiert'],
  ['organisieren', 'organise', 'Planung', 'Ich organisiere die Aufgaben im Jira-Board.', 'hat organisiert'],
  ['aufteilen', 'split / divide', 'Planung', 'Ich teile die große Aufgabe in kleinere Tickets auf.', 'hat aufgeteilt'],
  ['koordinieren', 'coordinate', 'Planung', 'Ich koordiniere die Arbeit zwischen Frontend und Backend.', 'hat koordiniert'],
  ['verwalten', 'manage', 'Planung', 'Ich verwalte die Aufgaben im Jira.', 'hat verwaltet'],
  ['liefern', 'deliver', 'Planung', 'Ich liefere das Feature pünktlich zum Sprint-Ende.', 'hat geliefert'],
  ['einhalten', 'meet / adhere to', 'Planung', 'Ich halte die Deadline ein.', 'hat eingehalten'],
  ['iterieren', 'iterate', 'Planung', 'Wir iterieren schnell und verbessern nach Feedback.', 'hat iteriert'],
  ['beheben', 'fix', 'Fehler', 'Ich behebe den Bug im Login-Prozess.', 'hat behoben'],
  ['lösen', 'solve', 'Fehler', 'Ich löse das Problem mit einem anderen Ansatz.', 'hat gelöst'],
  ['identifizieren', 'identify', 'Fehler', 'Ich identifiziere die Ursache des Fehlers.', 'hat identifiziert'],
  ['eingrenzen', 'narrow down', 'Fehler', 'Ich grenze das Problem auf eine Funktion ein.', 'hat eingegrenzt'],
  ['isolieren', 'isolate', 'Fehler', 'Ich isoliere den fehlerhaften Code.', 'hat isoliert'],
  ['korrigieren', 'correct', 'Fehler', 'Ich korrigiere den Logikfehler in der Berechnung.', 'hat korrigiert'],
  ['vermeiden', 'avoid', 'Fehler', 'Ich vermeide Race Conditions durch Locking.', 'hat vermieden'],
  ['verhindern', 'prevent', 'Fehler', 'Ich verhindere SQL-Injection durch Prepared Statements.', 'hat verhindert'],
  ['eskalieren', 'escalate', 'Fehler', 'Ich eskaliere das Problem an den Senior-Entwickler.', 'hat eskaliert'],
  ['arbeiten', 'work', 'Allgemein', 'Ich arbeite täglich mit dem Team zusammen.', 'hat gearbeitet'],
  ['lernen', 'learn', 'Allgemein', 'Ich lerne gerade Go für mein neues Projekt.', 'hat gelernt'],
  ['verstehen', 'understand', 'Allgemein', 'Ich verstehe die Anforderungen gut.', 'hat verstanden'],
  ['kennen', 'know', 'Allgemein', 'Ich kenne Laravel sehr gut.', 'hat gekannt'],
  ['beginnen', 'begin / start', 'Allgemein', 'Ich beginne mit der Implementierung des Features.', 'hat begonnen'],
  ['unterstützen', 'support', 'Allgemein', 'Ich unterstütze das Team bei der Migration.', 'hat unterstützt'],
  ['beitragen', 'contribute', 'Allgemein', 'Ich trage zum Open-Source-Projekt bei.', 'hat beigetragen'],
  ['übernehmen', 'take over', 'Allgemein', 'Ich übernehme die Aufgabe von meinem Kollegen.', 'hat übernommen'],
  ['zusammenarbeiten', 'collaborate', 'Allgemein', 'Ich arbeite eng mit dem Frontend-Team zusammen.', 'hat zusammengearbeitet'],
  ['nachfragen', 'follow up / ask', 'Allgemein', 'Ich frage nach, wenn etwas unklar ist.', 'hat nachgefragt'],
  ['sich einarbeiten', 'onboard / get up to speed', 'Allgemein', 'Ich arbeite mich schnell in das neue System ein.', 'hat sich eingearbeitet'],
  ['nachschlagen', 'look up', 'Allgemein', 'Ich schlage die Dokumentation nach.', 'hat nachgeschlagen'],
  ['herausfinden', 'find out', 'Allgemein', 'Ich finde heraus, warum die Pipeline fehlschlägt.', 'hat herausgefunden'],
  ['umsetzen', 'implement / put into practice', 'Allgemein', 'Ich setze die Anforderungen in Code um.', 'hat umgesetzt'],
  ['durchführen', 'carry out / perform', 'Allgemein', 'Ich führe das Code-Review durch.', 'hat durchgeführt'],
  ['einsetzen', 'use / deploy', 'Allgemein', 'Ich setze Docker für die Containerisierung ein.', 'hat eingesetzt'],
  ['anwenden', 'apply', 'Allgemein', 'Ich wende SOLID-Prinzipien im Code an.', 'hat angewendet'],
  ['achten auf', 'pay attention to', 'Allgemein', 'Ich achte auf die Sicherheit der API.', 'hat geachtet'],
  ['sorgen für', 'ensure / take care of', 'Allgemein', 'Ich sorge für eine saubere Code-Struktur.', 'hat gesorgt'],
  ['kümmern um', 'take care of', 'Allgemein', 'Ich kümmere mich um das Deployment.', 'hat sich gekümmert'],
  ['fokussieren auf', 'focus on', 'Allgemein', 'Ich fokussiere mich auf das Backend.', 'hat sich fokussiert'],
];

const NOUNS: Array<[string, string, string, string, string]> = [
  ['der Code', '(kein Pl.)', 'code', 'Code', 'Der Code ist sauber und gut strukturiert.'],
  ['die Funktion', '-en', 'function', 'Code', 'Ich schreibe eine Funktion für die Validierung.'],
  ['die Methode', '-n', 'method', 'Code', 'Die Methode gibt einen Boolean zurück.'],
  ['die Klasse', '-n', 'class', 'Code', 'Ich erstelle eine neue Klasse für den Service.'],
  ['das Objekt', '-e', 'object', 'Code', 'Ich instanziiere das Objekt im Konstruktor.'],
  ['die Variable', '-n', 'variable', 'Code', 'Ich deklariere die Variable am Anfang.'],
  ['der Parameter', '-', 'parameter', 'Code', 'Ich übergebe den Parameter an die Funktion.'],
  ['die Schleife', '-n', 'loop', 'Code', 'Die Schleife läuft durch alle Datensätze.'],
  ['die Ausnahme', '-n', 'exception', 'Code', 'Ich werfe eine Ausnahme bei ungültiger Eingabe.'],
  ['der Fehler', '-', 'error / bug', 'Code', 'Ich habe einen Fehler im Code gefunden.'],
  ['die Bibliothek', '-en', 'library', 'Code', 'Ich binde eine neue Bibliothek ein.'],
  ['das Framework', '-s', 'framework', 'Code', 'Laravel ist mein Haupt-Framework.'],
  ['das Modul', '-e', 'module', 'Code', 'Ich erstelle ein neues Modul für die Zahlung.'],
  ['die Schnittstelle', '-n', 'interface', 'Code', 'Ich definiere eine Schnittstelle für den Service.'],
  ['die Logik', '(kein Pl.)', 'logic', 'Code', 'Die Business-Logik liegt im Service-Layer.'],
  ['der Algorithmus', 'Algorithmen', 'algorithm', 'Code', 'Ich optimiere den Algorithmus für bessere Performance.'],
  ['die Dokumentation', '-en', 'documentation', 'Code', 'Ich schreibe eine Dokumentation für die API.'],
  ['die Refaktorierung', '-en', 'refactoring', 'Code', 'Die Refaktorierung verbessert die Lesbarkeit.'],
  ['die Wartbarkeit', '(kein Pl.)', 'maintainability', 'Code', 'Ich achte auf die Wartbarkeit des Systems.'],
  ['das Prinzip', '-ien', 'principle', 'Code', 'Ich halte SOLID-Prinzipien ein.'],
  ['die Qualität', '(kein Pl.)', 'quality', 'Code', 'Ich sorge für hohe Code-Qualität.'],
  ['die Struktur', '-en', 'structure', 'Code', 'Eine klare Struktur erleichtert die Zusammenarbeit.'],
  ['die Architektur', '-en', 'architecture', 'Architektur', 'Ich bin verantwortlich für die Backend-Architektur.'],
  ['der Service', '-s', 'service', 'Architektur', 'Ich baue einen neuen Microservice für die Zahlung.'],
  ['das Backend', '(kein Pl.)', 'backend', 'Architektur', 'Mein Fokus liegt auf dem Backend.'],
  ['das Frontend', '(kein Pl.)', 'frontend', 'Architektur', 'Das Frontend kommuniziert mit der REST-API.'],
  ['die API', '-s', 'API', 'Architektur', 'Ich designe eine RESTful API.'],
  ['der Endpunkt', '-e', 'endpoint', 'Architektur', 'Ich erstelle einen neuen API-Endpunkt.'],
  ['die Anfrage', '-n', 'request', 'Architektur', 'Der Server empfängt die Anfrage des Clients.'],
  ['die Antwort', '-en', 'response', 'Architektur', 'Die API sendet eine JSON-Antwort zurück.'],
  ['der Client', '-s', 'client', 'Architektur', 'Der Client sendet die Anfrage an den Server.'],
  ['der Server', '-', 'server', 'Architektur', 'Der Server verarbeitet alle Anfragen.'],
  ['die Middleware', '-s', 'middleware', 'Architektur', 'Die Middleware prüft den Token vor jedem Request.'],
  ['der Controller', '-', 'controller', 'Architektur', 'Der Controller verarbeitet die eingehende Anfrage.'],
  ['das Token', '-s', 'token', 'Architektur', 'Ich prüfe das JWT-Token bei jeder Anfrage.'],
  ['die Authentifizierung', '(kein Pl.)', 'authentication', 'Architektur', 'Die Authentifizierung läuft über JWT.'],
  ['die Konfiguration', '-en', 'configuration', 'Architektur', 'Ich lese die Konfiguration aus der .env-Datei.'],
  ['die Tabelle', '-n', 'table', 'Datenbank', 'Die Tabelle speichert alle Benutzer.'],
  ['der Datensatz', '¨-e', 'record', 'Datenbank', 'Ich füge einen neuen Datensatz ein.'],
  ['der Primärschlüssel', '-', 'primary key', 'Datenbank', 'Die ID ist der Primärschlüssel der Tabelle.'],
  ['der Fremdschlüssel', '-', 'foreign key', 'Datenbank', 'Der Fremdschlüssel verbindet zwei Tabellen.'],
  ['der Index', 'Indizes', 'index', 'Datenbank', 'Ich erstelle einen Index für schnellere Abfragen.'],
  ['die Abfrage', '-n', 'query', 'Datenbank', 'Die Abfrage dauert zu lange — ich optimiere sie.'],
  ['die Transaktion', '-en', 'transaction', 'Datenbank', 'Ich nutze eine Transaktion für atomare Operationen.'],
  ['die Migration', '-en', 'migration', 'Datenbank', 'Ich führe die Datenbank-Migration aus.'],
  ['das Schema', '-ta', 'schema', 'Datenbank', 'Das Datenbankschema beschreibt alle Tabellen.'],
  ['das Backup', '-s', 'backup', 'Datenbank', 'Ich mache täglich ein Backup der Datenbank.'],
  ['die Pipeline', '-n', 'pipeline', 'DevOps', 'Ich baue eine CI/CD-Pipeline mit GitHub Actions.'],
  ['das Deployment', '-s', 'deployment', 'DevOps', 'Das Deployment läuft automatisch nach dem Merge.'],
  ['der Container', '-', 'container', 'DevOps', 'Ich starte den Docker-Container.'],
  ['das Image', '-s', 'image', 'DevOps', 'Ich baue ein neues Docker-Image.'],
  ['die Umgebung', '-en', 'environment', 'DevOps', 'Ich teste in der Staging-Umgebung.'],
  ['die Version', '-en', 'version', 'DevOps', 'Ich aktualisiere die Version in der package.json.'],
  ['das Repository', '-s', 'repository', 'DevOps', 'Ich pushe den Code ins GitHub-Repository.'],
  ['der Branch', '-es', 'branch', 'DevOps', 'Ich erstelle einen neuen Branch für das Feature.'],
  ['der Commit', '-s', 'commit', 'DevOps', 'Ich mache einen Commit nach jeder Änderung.'],
  ['der Pull Request', '-s', 'pull request', 'DevOps', 'Ich öffne einen Pull Request für das neue Feature.'],
  ['das Secret', '-s', 'secret', 'DevOps', 'Ich speichere den API-Key als Secret in GitHub.'],
  ['das Monitoring', '(kein Pl.)', 'monitoring', 'DevOps', 'Das Monitoring zeigt die CPU-Auslastung in Echtzeit.'],
  ['das Log', '-s', 'log', 'DevOps', 'Ich lese die Logs, um den Fehler zu finden.'],
  ['der Rollback', '-s', 'rollback', 'DevOps', 'Wir führen einen Rollback durch.'],
  ['der Sprint', '-s', 'sprint', 'Agile', 'Der Sprint dauert zwei Wochen.'],
  ['das Backlog', '-s', 'backlog', 'Agile', 'Das Backlog enthält alle offenen Aufgaben.'],
  ['das Ticket', '-s', 'ticket', 'Agile', 'Ich bearbeite das Ticket aus dem aktuellen Sprint.'],
  ['die User Story', '-s', 'user story', 'Agile', 'Die User Story beschreibt den Nutzen.'],
  ['die Schätzung', '-en', 'estimate', 'Agile', 'Meine Schätzung für das Feature sind drei Tage.'],
  ['das Standup', '-s', 'standup', 'Agile', 'Im täglichen Standup berichte ich über meinen Fortschritt.'],
  ['die Retrospektive', '-n', 'retrospective', 'Agile', 'In der Retrospektive besprechen wir Verbesserungen.'],
  ['die Anforderung', '-en', 'requirement', 'Agile', 'Ich kläre die Anforderungen mit dem Product Owner.'],
  ['das Feedback', '(kein Pl.)', 'feedback', 'Agile', 'Ich gebe Feedback im Code-Review.'],
  ['der Bug', '-s', 'bug', 'Fehler', 'Ich finde und behebe den Bug im Code.'],
  ['die Fehlermeldung', '-en', 'error message', 'Fehler', 'Die Fehlermeldung hilft beim Debuggen.'],
  ['die Ursache', '-n', 'root cause', 'Fehler', 'Ich suche die Ursache des Problems.'],
  ['der Fix', '-es', 'fix', 'Fehler', 'Der Fix ist fertig und wartet auf Review.'],
  ['der Grenzfall', '¨-e', 'edge case', 'Fehler', 'Ich teste alle Grenzfälle in den Unit Tests.'],
  ['das Team', '-s', 'team', 'Team', 'Ich arbeite in einem agilen Entwicklungsteam.'],
  ['der Kollege', '-n', 'colleague (m)', 'Team', 'Mein Kollege reviewt meinen Code.'],
  ['die Deadline', '-s', 'deadline', 'Team', 'Ich halte die Deadline immer ein.'],
  ['die Lösung', '-en', 'solution', 'Team', 'Ich schlage eine technische Lösung vor.'],
  ['das Projekt', '-e', 'project', 'Allgemein', 'Ich arbeite gerade an einem spannenden Projekt.'],
  ['das Feature', '-s', 'feature', 'Allgemein', 'Das neue Feature ist in zwei Tagen fertig.'],
  ['der Nutzer', '-', 'user', 'Allgemein', 'Der Nutzer meldet sich mit E-Mail und Passwort an.'],
  ['die Erfahrung', '-en', 'experience', 'Allgemein', 'Ich habe zwei Jahre Erfahrung mit Laravel.'],
  ['die Kenntnisse', '(Pl.)', 'knowledge / skills', 'Allgemein', 'Meine Kenntnisse in Java sind solide.'],
  ['die Herausforderung', '-en', 'challenge', 'Allgemein', 'Die größte Herausforderung war die Performance.'],
  ['das Ziel', '-e', 'goal', 'Allgemein', 'Mein Ziel ist, ein guter Full-Stack-Entwickler zu werden.'],
  ['die Verbesserung', '-en', 'improvement', 'Allgemein', 'Ich schlage eine Verbesserung der Datenbankabfrage vor.'],
  ['der Ansatz', '¨-e', 'approach', 'Allgemein', 'Ich wähle einen einfachen Ansatz.'],
  ['die Entscheidung', '-en', 'decision', 'Allgemein', 'Ich treffe die Entscheidung nach einem kurzen Test.'],
  ['die Priorität', '-en', 'priority', 'Allgemein', 'Dieser Bug hat höchste Priorität.'],
  ['die Analyse', '-n', 'analysis', 'Allgemein', 'Ich mache eine kurze Analyse des Problems.'],
];

const ADJS: Array<[string, string, string, string, string]> = [
  ['skalierbar', 'scalable', 'nicht skalierbar', 'Technik', 'Das System ist skalierbar und wächst mit den Nutzerzahlen.'],
  ['wartbar', 'maintainable', 'unwartbar', 'Technik', 'Ich schreibe wartbaren Code mit klaren Strukturen.'],
  ['performant', 'high-performing', 'langsam', 'Technik', 'Die API ist sehr performant — unter 50ms Antwortzeit.'],
  ['stabil', 'stable', 'instabil', 'Technik', 'Das System ist stabil und läuft ohne Ausfälle.'],
  ['robust', 'robust', 'fragil', 'Technik', 'Die Architektur ist robust gegen Fehler.'],
  ['zuverlässig', 'reliable', 'unzuverlässig', 'Technik', 'Das Deployment läuft zuverlässig ohne manuelle Eingriffe.'],
  ['effizient', 'efficient', 'ineffizient', 'Technik', 'Der Algorithmus ist effizient und spart Ressourcen.'],
  ['automatisiert', 'automated', 'manuell', 'Technik', 'Der Testprozess ist vollständig automatisiert.'],
  ['containerisiert', 'containerised', 'nicht containerisiert', 'Technik', 'Die App ist containerisiert und läuft in Docker.'],
  ['modular', 'modular', 'monolithisch', 'Technik', 'Die Anwendung ist modular aufgebaut.'],
  ['lesbar', 'readable', 'unleserlich', 'Technik', 'Der Code ist gut lesbar und verständlich.'],
  ['testbar', 'testable', 'nicht testbar', 'Technik', 'Ich schreibe testbaren Code mit klaren Abhängigkeiten.'],
  ['dokumentiert', 'documented', 'undokumentiert', 'Technik', 'Die API ist gut dokumentiert.'],
  ['optimiert', 'optimised', 'unoptimiert', 'Technik', 'Die Datenbankabfrage ist für Performance optimiert.'],
  ['strukturiert', 'structured', 'unstrukturiert', 'Technik', 'Das Projekt ist gut strukturiert.'],
  ['asynchron', 'asynchronous', 'synchron', 'Technik', 'Ich verarbeite E-Mails asynchron über eine Queue.'],
  ['konsistent', 'consistent', 'inkonsistent', 'Technik', 'Die Daten sind konsistent über alle Services.'],
  ['portabel', 'portable', 'plattformabhängig', 'Technik', 'Docker macht die App portabel auf allen Systemen.'],
  ['wiederverwendbar', 'reusable', 'einmalig', 'Technik', 'Ich schreibe wiederverwendbare Komponenten.'],
  ['erweiterbar', 'extensible', 'starr', 'Technik', 'Das System ist erweiterbar für neue Features.'],
  ['hochverfügbar', 'highly available', 'fehleranfällig', 'Technik', 'Die Cloud-Infrastruktur ist hochverfügbar.'],
  ['gut', 'good', 'schlecht', 'Qualität', 'Der Code ist gut strukturiert und leicht zu lesen.'],
  ['sauber', 'clean', 'chaotisch', 'Qualität', 'Ich schreibe sauberen Code nach Clean-Code-Regeln.'],
  ['klar', 'clear', 'unklar', 'Qualität', 'Die Anforderungen sind klar definiert.'],
  ['präzise', 'precise', 'ungenau', 'Qualität', 'Die Fehlermeldung ist präzise und hilfreich.'],
  ['korrekt', 'correct', 'falsch', 'Qualität', 'Das Ergebnis ist korrekt und entspricht dem Test.'],
  ['vollständig', 'complete', 'unvollständig', 'Qualität', 'Die Dokumentation ist vollständig.'],
  ['fehlerhaft', 'faulty / buggy', 'fehlerfrei', 'Qualität', 'Der fehlerhafte Code muss refaktoriert werden.'],
  ['fehlerfrei', 'error-free', 'fehlerhaft', 'Qualität', 'Der Code ist nach dem Review fehlerfrei.'],
  ['professionell', 'professional', 'unprofessionell', 'Qualität', 'Wir liefern professionelle Arbeit ab.'],
  ['solide', 'solid', 'schwach', 'Qualität', 'Meine Kenntnisse in Python sind solide.'],
  ['aussagekräftig', 'meaningful', 'nichtssagend', 'Qualität', 'Ich wähle aussagekräftige Variablennamen.'],
  ['verständlich', 'understandable', 'unverständlich', 'Qualität', 'Der Code ist gut verständlich ohne viele Kommentare.'],
  ['schnell', 'fast', 'langsam', 'Zeit', 'Die API antwortet sehr schnell.'],
  ['langsam', 'slow', 'schnell', 'Zeit', 'Die Datenbankabfrage ist zu langsam.'],
  ['pünktlich', 'on time', 'verspätet', 'Zeit', 'Ich liefere das Feature pünktlich ab.'],
  ['aktuell', 'current / up to date', 'veraltet', 'Zeit', 'Die Dokumentation ist nicht mehr aktuell.'],
  ['veraltet', 'outdated', 'aktuell', 'Zeit', 'Die Bibliothek ist veraltet — ich aktualisiere sie.'],
  ['neu', 'new', 'alt', 'Zeit', 'Ich implementiere eine neue Funktion.'],
  ['modern', 'modern', 'veraltet', 'Zeit', 'Wir nutzen moderne Technologien.'],
  ['kontinuierlich', 'continuous', 'unterbrochen', 'Zeit', 'Wir verbessern das System kontinuierlich.'],
  ['fertig', 'ready / done', 'unfertig', 'Zeit', 'Das Ticket ist fertig für den Review.'],
  ['dringend', 'urgent', 'nicht dringend', 'Zeit', 'Das ist ein dringender Bug in der Produktion.'],
  ['groß', 'large / big', 'klein', 'Größe', 'Das ist ein großes Projekt mit vielen Abhängigkeiten.'],
  ['klein', 'small', 'groß', 'Größe', 'Ich teile die Aufgabe in kleine Tickets auf.'],
  ['einfach', 'simple / easy', 'komplex', 'Größe', 'Ich wähle den einfachsten Ansatz.'],
  ['komplex', 'complex', 'einfach', 'Größe', 'Die Architektur ist komplex aber gut dokumentiert.'],
  ['minimal', 'minimal', 'umfangreich', 'Größe', 'Ich mache minimale Änderungen für den Fix.'],
  ['hoch', 'high', 'niedrig', 'Größe', 'Die Testabdeckung ist hoch.'],
  ['motiviert', 'motivated', 'demotiviert', 'Gefühl', 'Ich bin sehr motiviert, bei COLNEO zu arbeiten.'],
  ['begeistert', 'enthusiastic', 'desinteressiert', 'Gefühl', 'Ich bin begeistert von der BIM-Technologie.'],
  ['offen', 'open', 'geschlossen', 'Gefühl', 'Ich bin offen für Feedback und neue Ansätze.'],
  ['bereit', 'ready / willing', 'nicht bereit', 'Gefühl', 'Ich bin bereit, Java schnell zu lernen.'],
  ['zuversichtlich', 'confident', 'unsicher', 'Gefühl', 'Ich bin zuversichtlich, dass ich mich schnell einarbeite.'],
  ['fokussiert', 'focused', 'abgelenkt', 'Gefühl', 'Ich bin sehr fokussiert auf meine Aufgaben.'],
  ['engagiert', 'committed / engaged', 'gleichgültig', 'Gefühl', 'Ich bin engagiert und arbeite selbstständig.'],
  ['ehrlich', 'honest', 'unehrlich', 'Gefühl', 'Ich bin ehrlich über meine Stärken und Schwächen.'],
  ['lernbereit', 'willing to learn', 'lernfaul', 'Gefühl', 'Ich bin sehr lernbereit und arbeite mich schnell ein.'],
  ['flexibel', 'flexible', 'starr', 'Gefühl', 'Ich bin flexibel bei Aufgaben und Technologien.'],
  ['selbstständig', 'independent', 'abhängig', 'Charakter', 'Ich arbeite selbstständig ohne viel Aufsicht.'],
  ['teamfähig', 'team-oriented', 'einzelgängerisch', 'Charakter', 'Ich bin sehr teamfähig und kommuniziere offen.'],
  ['verantwortungsbewusst', 'responsible', 'verantwortungslos', 'Charakter', 'Ich bin verantwortungsbewusst bei Deployments.'],
  ['sorgfältig', 'careful / thorough', 'nachlässig', 'Charakter', 'Ich arbeite sorgfältig und prüfe alles vor dem Merge.'],
  ['analytisch', 'analytical', 'intuitiv', 'Charakter', 'Ich denke analytisch und strukturiere Probleme.'],
  ['detailorientiert', 'detail-oriented', 'oberflächlich', 'Charakter', 'Ich bin sehr detailorientiert beim Code-Review.'],
  ['lösungsorientiert', 'solution-oriented', 'problemorientiert', 'Charakter', 'Ich bin lösungsorientiert — ich suche Wege, nicht Ausreden.'],
  ['proaktiv', 'proactive', 'reaktiv', 'Charakter', 'Ich bin proaktiv und spreche Probleme früh an.'],
  ['kommunikativ', 'communicative', 'verschlossen', 'Charakter', 'Ich bin kommunikativ und halte das Team informiert.'],
  ['belastbar', 'resilient', 'empfindlich', 'Charakter', 'Ich bin belastbar und arbeite gut unter Druck.'],
  ['anpassungsfähig', 'adaptable', 'starr', 'Charakter', 'Ich bin anpassungsfähig in neuen Technologien.'],
  ['wichtig', 'important', 'unwichtig', 'Bewertung', 'Tests sind sehr wichtig für die Codequalität.'],
  ['relevant', 'relevant', 'irrelevant', 'Bewertung', 'Das Feedback ist sehr relevant für das Design.'],
  ['kritisch', 'critical', 'unkritisch', 'Bewertung', 'Das ist ein kritischer Bug in der Produktion.'],
  ['optimal', 'optimal', 'suboptimal', 'Bewertung', 'Das ist die optimale Lösung für dieses Problem.'],
  ['ideal', 'ideal', 'schlecht', 'Bewertung', 'Docker ist ideal für konsistente Umgebungen.'],
  ['sinnvoll', 'sensible / meaningful', 'sinnlos', 'Bewertung', 'Das Refactoring ist sinnvoll für die Wartbarkeit.'],
  ['nützlich', 'useful', 'nutzlos', 'Bewertung', 'Das Tool ist sehr nützlich für das Debugging.'],
  ['erfolgreich', 'successful', 'erfolglos', 'Bewertung', 'Das Deployment war erfolgreich.'],
  ['realistisch', 'realistic', 'unrealistisch', 'Bewertung', 'Drei Tage für dieses Feature ist realistisch.'],
  ['machbar', 'feasible / doable', 'unmöglich', 'Bewertung', 'Das Feature ist in zwei Wochen machbar.'],
  ['spannend', 'exciting', 'langweilig', 'Allgemein', 'Die Arbeit bei COLNEO klingt sehr spannend.'],
  ['innovativ', 'innovative', 'konservativ', 'Allgemein', 'COLNEO entwickelt innovative BIM-Lösungen.'],
  ['praktisch', 'practical', 'theoretisch', 'Allgemein', 'Ich habe praktische Erfahrung mit Docker.'],
  ['grundlegend', 'fundamental / basic', 'fortgeschritten', 'Allgemein', 'Ich kenne die grundlegenden Konzepte von Java.'],
  ['erfahren', 'experienced', 'unerfahren', 'Allgemein', 'Ich bin erfahren im Umgang mit REST-APIs.'],
  ['vertraut', 'familiar', 'unbekannt', 'Allgemein', 'Ich bin vertraut mit agilen Entwicklungsmethoden.'],
  ['notwendig', 'necessary', 'unnötig', 'Allgemein', 'Eine gute Testabdeckung ist notwendig.'],
  ['hilfreich', 'helpful', 'nutzlos', 'Allgemein', 'Gute Dokumentation ist sehr hilfreich.'],
  ['transparent', 'transparent', 'undurchsichtig', 'Allgemein', 'Ich arbeite transparent und kommuniziere offen.'],
  ['herausfordernd', 'challenging', 'einfach', 'Allgemein', 'BIM zu lernen ist herausfordernd aber machbar.'],
  ['abwechslungsreich', 'varied', 'monoton', 'Allgemein', 'Meine Arbeit bei VW ist sehr abwechslungsreich.'],
  ['wertvoll', 'valuable', 'wertlos', 'Allgemein', 'Code-Reviews sind wertvoll für die Qualität.'],
  ['nachhaltig', 'sustainable', 'kurzfristig', 'Allgemein', 'Ich suche nachhaltige Lösungen, keine Quick Fixes.'],
];

const SENTS: Array<[string, string, string, string, string, string]> = [
  ['Ich entwickle skalierbare Backend-Systeme mit Laravel.', 'I develop scalable backend systems with Laravel.', 'entwickeln', 'Backend-System', 'skalierbar', 'Entwicklung'],
  ['Ich implementiere eine neue Funktion im aktuellen Sprint.', 'I implement a new feature in the current sprint.', 'implementieren', 'Funktion', 'aktuell', 'Entwicklung'],
  ['Ich schreibe sauberen, wartbaren Code nach SOLID-Prinzipien.', 'I write clean, maintainable code following SOLID principles.', 'schreiben', 'Code', 'sauber', 'Entwicklung'],
  ['Ich baue eine robuste REST-API für die interne Kommunikation.', 'I build a robust REST API for internal communication.', 'bauen', 'API', 'robust', 'Entwicklung'],
  ['Ich refaktoriere den alten, fehlerhaften Code im Backend.', 'I refactor the old, buggy code in the backend.', 'refaktorieren', 'Code', 'fehlerhaft', 'Entwicklung'],
  ['Ich erstelle eine wiederverwendbare Komponente im Frontend.', 'I create a reusable component in the frontend.', 'erstellen', 'Komponente', 'wiederverwendbar', 'Entwicklung'],
  ['Ich optimiere den langsamen Algorithmus für bessere Performance.', 'I optimise the slow algorithm for better performance.', 'optimieren', 'Algorithmus', 'langsam', 'Entwicklung'],
  ['Ich integriere einen externen Service über eine dokumentierte Schnittstelle.', 'I integrate an external service via a documented interface.', 'integrieren', 'Schnittstelle', 'dokumentiert', 'Entwicklung'],
  ['Ich strukturiere das Projekt modular, damit es erweiterbar bleibt.', 'I structure the project modularly so it stays extensible.', 'strukturieren', 'Projekt', 'modular', 'Entwicklung'],
  ['Ich entwickle das neue Feature iterativ und liefere schnell Ergebnisse.', 'I develop the new feature iteratively and deliver results quickly.', 'entwickeln', 'Feature', 'iterativ', 'Entwicklung'],
  ['Ich teste alle kritischen Funktionen mit automatisierten Unit Tests.', 'I test all critical functions with automated unit tests.', 'testen', 'Funktion', 'automatisiert', 'Testing'],
  ['Ich debugge den fehlerhaften Code mithilfe des Stack Trace.', 'I debug the buggy code using the stack trace.', 'debuggen', 'Code', 'fehlerhaft', 'Testing'],
  ['Ich validiere die vollständige Eingabe des Nutzers vor der Verarbeitung.', "I validate the user's complete input before processing.", 'validieren', 'Eingabe', 'vollständig', 'Testing'],
  ['Ich analysiere die langsamen Datenbankabfragen mit einem Profiling-Tool.', 'I analyse the slow database queries with a profiling tool.', 'analysieren', 'Abfrage', 'langsam', 'Testing'],
  ['Ich stelle sicher, dass alle kritischen Pfade abgedeckt sind.', 'I ensure that all critical paths are covered.', 'sicherstellen', 'Pfad', 'kritisch', 'Testing'],
  ['Ich messe die aktuelle Antwortzeit der API nach dem Update.', 'I measure the current response time of the API after the update.', 'messen', 'Antwortzeit', 'aktuell', 'Testing'],
  ['Ich deploye die neue, stabile Version auf die Produktionsumgebung.', 'I deploy the new, stable version to the production environment.', 'deployen', 'Version', 'stabil', 'Deployment'],
  ['Ich automatisiere das vollständige Deployment mit GitHub Actions.', 'I automate the complete deployment with GitHub Actions.', 'automatisieren', 'Deployment', 'vollständig', 'Deployment'],
  ['Ich konfiguriere die sichere Cloud-Infrastruktur für das neue Release.', 'I configure the secure cloud infrastructure for the new release.', 'konfigurieren', 'Infrastruktur', 'sicher', 'Deployment'],
  ['Ich führe einen schnellen Rollback durch, weil das Update fehlerhaft war.', 'I perform a quick rollback because the update was faulty.', 'zurückrollen', 'Rollback', 'fehlerhaft', 'Deployment'],
  ['Ich speichere die strukturierten Daten in der relationalen Datenbank.', 'I store the structured data in the relational database.', 'speichern', 'Datenbank', 'strukturiert', 'Datenbank'],
  ['Ich optimiere die langsame Datenbankabfrage mit einem Index.', 'I optimise the slow database query with an index.', 'optimieren', 'Abfrage', 'langsam', 'Datenbank'],
  ['Ich führe eine sichere Transaktion für atomare Datenbankoperationen aus.', 'I execute a secure transaction for atomic database operations.', 'ausführen', 'Transaktion', 'sicher', 'Datenbank'],
  ['Ich cache häufige Datenbankabfragen mit Redis für schnelle Antworten.', 'I cache frequent database queries with Redis for fast responses.', 'cachen', 'Abfrage', 'häufig', 'Datenbank'],
  ['Ich verschlüssele die privaten Passwörter mit bcrypt vor dem Speichern.', 'I encrypt the private passwords with bcrypt before saving.', 'verschlüsseln', 'Passwort', 'privat', 'Datenbank'],
  ['Ich baue eine skalierbare Microservice-Architektur für das Produkt.', 'I build a scalable microservice architecture for the product.', 'bauen', 'Architektur', 'skalierbar', 'Architektur'],
  ['Ich implementiere eine sichere JWT-Authentifizierung für die API.', 'I implement a secure JWT authentication for the API.', 'implementieren', 'Authentifizierung', 'sicher', 'Architektur'],
  ['Ich konfiguriere die hochverfügbare Cloud-Infrastruktur mit AWS.', 'I configure the highly available cloud infrastructure with AWS.', 'konfigurieren', 'Infrastruktur', 'hochverfügbar', 'Architektur'],
  ['Ich nutze eine asynchrone Queue für die aufwendige E-Mail-Verarbeitung.', 'I use an asynchronous queue for the email processing.', 'nutzen', 'Queue', 'asynchron', 'Architektur'],
  ['Ich sichere alle privaten API-Endpunkte mit einer Auth-Middleware.', 'I secure all private API endpoints with an auth middleware.', 'absichern', 'Endpunkt', 'privat', 'Architektur'],
  ['Ich priorisiere die wichtigen Tickets im wöchentlichen Sprint Planning.', 'I prioritise the important tickets in the weekly sprint planning.', 'priorisieren', 'Ticket', 'wichtig', 'Agile'],
  ['Ich berichte täglich über den aktuellen Fortschritt im Standup.', 'I report daily on the current progress in the standup.', 'berichten', 'Fortschritt', 'aktuell', 'Agile'],
  ['Ich liefere das fertige Feature pünktlich zum Sprintende.', 'I deliver the finished feature on time at the end of the sprint.', 'liefern', 'Feature', 'fertig', 'Agile'],
  ['Ich kläre die unklaren Anforderungen direkt mit dem Product Owner.', 'I clarify the unclear requirements directly with the product owner.', 'klären', 'Anforderung', 'unklar', 'Agile'],
  ['Ich iteriere schnell und verbessere das Feature nach dem Feedback.', 'I iterate quickly and improve the feature based on feedback.', 'iterieren', 'Feature', 'schnell', 'Agile'],
  ['Ich automatisiere das vollständige Deployment mit einer CI/CD-Pipeline.', 'I automate the complete deployment with a CI/CD pipeline.', 'automatisieren', 'Pipeline', 'vollständig', 'DevOps'],
  ['Ich überwache die aktive Cloud-Infrastruktur mit einem Monitoring-Tool.', 'I monitor the active cloud infrastructure with a monitoring tool.', 'überwachen', 'Infrastruktur', 'aktiv', 'DevOps'],
  ['Ich führe den schnellen Rollback nach dem fehlerhaften Update durch.', 'I carry out the quick rollback after the faulty update.', 'durchführen', 'Rollback', 'fehlerhaft', 'DevOps'],
  ['Ich speichere den privaten API-Schlüssel als sicheres Secret.', 'I store the private API key as a secure secret.', 'speichern', 'Secret', 'privat', 'DevOps'],
  ['Ich merge den stabilen Feature-Branch nach dem erfolgreichen Review.', 'I merge the stable feature branch after the successful review.', 'mergen', 'Branch', 'stabil', 'DevOps'],
  ['Ich arbeite täglich eng und kommunikativ mit dem agilen Team zusammen.', 'I work closely and communicatively with the agile team every day.', 'zusammenarbeiten', 'Team', 'kommunikativ', 'Team'],
  ['Ich gebe konstruktives, hilfreiches Feedback im technischen Code-Review.', 'I give constructive, helpful feedback in the technical code review.', 'geben', 'Feedback', 'konstruktiv', 'Team'],
  ['Ich übernehme die volle Verantwortung für das kritische Deployment.', 'I take full responsibility for the critical deployment.', 'übernehmen', 'Verantwortung', 'kritisch', 'Team'],
  ['Ich kommuniziere offen und direkt mit dem gesamten Scrum-Team.', 'I communicate openly and directly with the entire Scrum team.', 'kommunizieren', 'Team', 'direkt', 'Team'],
  ['Ich arbeite selbstständig und liefere zuverlässige Ergebnisse.', 'I work independently and deliver reliable results.', 'arbeiten', 'Ergebnis', 'selbstständig', 'Team'],
  ['Ich bin sehr motiviert, bei COLNEO innovative BIM-Software zu entwickeln.', 'I am very motivated to develop innovative BIM software at COLNEO.', 'entwickeln', 'Software', 'motiviert', 'Interview'],
  ['Ich bringe solide technische Kenntnisse und echte Lernbereitschaft mit.', 'I bring solid technical knowledge and genuine willingness to learn.', 'mitbringen', 'Kenntnisse', 'lernbereit', 'Interview'],
  ['Ich bin offen für konstruktives Feedback und neue technische Herausforderungen.', 'I am open to constructive feedback and new technical challenges.', 'sein', 'Feedback', 'offen', 'Interview'],
  ['Ich bin begeistert von der spannenden BIM-Technologie und lerne schnell.', 'I am enthusiastic about the exciting BIM technology and learn quickly.', 'lernen', 'Technologie', 'spannend', 'Interview'],
  ['Ich bin zuversichtlich, die technischen Anforderungen der Stelle zu erfüllen.', 'I am confident about meeting the technical requirements of the position.', 'erfüllen', 'Anforderung', 'zuversichtlich', 'Interview'],
  ['Ich bin teamfähig und arbeite gern in einem agilen, modernen Team.', 'I am a team player and enjoy working in an agile, modern team.', 'arbeiten', 'Team', 'teamfähig', 'Interview'],
  ['Ich bin ehrlich über meine soliden Stärken und offenen Schwächen.', 'I am honest about my solid strengths and open weaknesses.', 'sein', 'Stärke', 'ehrlich', 'Interview'],
  ['Ich bin bereit, die neuen BIM-Kenntnisse schnell und eigeninitiativ aufzubauen.', 'I am ready to build up the new BIM knowledge quickly and on my own initiative.', 'aufbauen', 'Kenntnisse', 'bereit', 'Interview'],
  ['Ich wechsle zu COLNEO, weil ich direkten Einfluss auf das innovative Produkt haben möchte.', 'I am moving to COLNEO because I want direct influence on the innovative product.', 'haben', 'Einfluss', 'direkt', 'Interview'],
  ['Ich bin proaktiv und spreche technische Probleme frühzeitig im Team an.', 'I am proactive and address technical problems early in the team.', 'ansprechen', 'Problem', 'proaktiv', 'Interview'],
  ['Ich freue mich auf die spannende, abwechslungsreiche Arbeit bei COLNEO.', 'I look forward to the exciting, varied work at COLNEO.', 'freuen', 'Arbeit', 'abwechslungsreich', 'Interview'],
];

async function run() {
  const uri = process.env.MONGO_URI || 'mongodb://localhost:27017/deutsch_trainer';
  await mongoose.connect(uri);
  console.log('Connected to MongoDB');

  let v = 0;
  for (const [infinitiv, english, category, example, perfekt] of VERBS) {
    await Verb.findOneAndUpdate(
      { infinitiv },
      { $set: { english, perfekt, category, example }, $setOnInsert: { practiced: false, lastPracticed: null } },
      { upsert: true, new: true },
    );
    v++;
  }
  console.log(`Upserted ${v} verbs`);

  let n = 0;
  for (const [word, plural, english, category, example] of NOUNS) {
    await Noun.findOneAndUpdate(
      { word },
      { $set: { plural, english, category, example }, $setOnInsert: { practiced: false, lastPracticed: null } },
      { upsert: true, new: true },
    );
    n++;
  }
  console.log(`Upserted ${n} nouns`);

  let a = 0;
  for (const [word, english, opposite, category, example] of ADJS) {
    await Adjective.findOneAndUpdate(
      { word },
      { $set: { english, opposite, category, example }, $setOnInsert: { practiced: false, lastPracticed: null } },
      { upsert: true, new: true },
    );
    a++;
  }
  console.log(`Upserted ${a} adjectives`);

  let s = 0;
  for (const [german, english, verbUsed, nounUsed, adjUsed, category] of SENTS) {
    await Sentence.findOneAndUpdate(
      { german },
      { $set: { english, verbUsed, nounUsed, adjUsed, category }, $setOnInsert: { practiced: false, lastPracticed: null } },
      { upsert: true, new: true },
    );
    s++;
  }
  console.log(`Upserted ${s} sentences`);

  await mongoose.disconnect();
  console.log('Extra seed complete!');
}

run().catch((err) => {
  console.error('Extra seed error:', err);
  process.exit(1);
});
